from datetime import datetime
from pathlib import Path

import openai

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

from dotenv import load_dotenv
load_dotenv()

def packaging_agent(
    product: dict,
    trend_summary: str,
    image_path: str,
    caption: str,
    tagline: str,
    quote: str,
    cta: str,
    hashtags: list,
    ad_copy_short: str,
    ad_copy_long: str,
    justification: str,
    filters: dict,
    stream_callback=None,
) -> str:
    """
    Packages all campaign assets into a professional markdown report.

    Returns:
        str: path to the saved .md report file.
    """

    import os
    import openai
    client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    def _log(step, data):
        if stream_callback:
            stream_callback(step, data)

    _log("start", "📦 Packaging Agent assembling final campaign report...")

    # Polish trend summary for executive audience
    polished = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "system",
                "content": "You are a marketing communications expert writing executive-ready campaign briefs.",
            },
            {
                "role": "user",
                "content": (
                    f"Rewrite this trend analysis as a concise, polished executive brief (max 150 words). "
                    f"Use professional language without bullet points:\n\n{trend_summary[:1500]}"
                ),
            },
        ],
    ).choices[0].message.content.strip()

    hashtag_str = " ".join(hashtags) if hashtags else ""
    image_abs = Path(image_path).resolve()

    report = f"""# 🛍️ Campaign Brief — {product['name']}
*Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}*

---

## 🎯 Campaign Overview

| Field | Value |
|-------|-------|
| **Product** | {product['name']} |
| **Brand** | {product.get('brand','—')} |
| **Category** | {product.get('category_name','—')} |
| **Price** | ${product.get('price',0):.2f} |
| **Target Audience** | {filters.get('gender','All')} · {filters.get('age_group','All')} · {filters.get('season','All')} season |
| **Campaign Goal** | {filters.get('campaign_goal','Brand Awareness')} |
| **Brand Tone** | {filters.get('tone','Modern & Aspirational')} |

---

## 📊 Market Intelligence

{polished}

---

## 🖼️ Campaign Visual

![Campaign Image]({image_abs})

---

## ✍️ Campaign Copy

### Hero Quote
> **"{quote}"**

### Tagline
*{tagline}*

### Caption
{caption}

### Call to Action
**{cta}**

---

## 📱 Ad Copy Variants

### Social Media (Short)
{ad_copy_short}

### Email / Landing Page
{ad_copy_long}

### Hashtags
{hashtag_str}

---

## ✅ Strategic Justification

{justification}

---

*Report generated by Campaign Agent · Confidential*
"""

    sku = product.get("sku", "product").replace("-", "_").lower()
    filename = f"campaign_report_{sku}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path = OUTPUT_DIR / filename

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)

    _log("done", f"📄 Report saved → `{report_path}`")
    return str(report_path)